name: Update Submodule content

on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout knmt website and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Make sure submodules are fetched

    - name: Pull latest changes
      run: |
        cd content  # Navigate to submodule directory
        git pull origin main --allow-unrelated-histories  # Pull latest changes and allow unrelated histories
        cd ..  # Go back to the parent repo 

    - name: Commit and push the updated submodule
      run: |
        git add content  # Stage the updated submodule changes
        git commit -m "github action :: Update submodule content to latest" || echo "No changes to commit"
        git push https://$GITHUB_ACTOR:${{ secrets.A_PUSH_TOKEN }}@github.com/ronia-jakim/knmt-website.git

