name: Update Submodule content

on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout knmt website and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Make sure submodules are fetched
    
    - name: Set Git user name and email
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Checkout correct branch for Repo knmt-website
      run: |
        git checkout main  # Or your specific branch
        git pull origin main  # Make sure Repo knmt-website is up to date

    - name: Checkout correct branch for the submodule 
      run: |
        cd content  # Go into submodule directory
        git checkout main  # Or your specific branch
        git pull origin main  # Pull latest changes from the submodule

    - name: Stage submodule changes
      run: |
        git add content  # Stage the submodule changes (updated reference)

    - name: Commit and push submodule update
      run: |
        git commit -m "github action :: Update submodule content to latest" || echo "No changes to commit"

    - name: Push changes to Repo knmt website
      env:
        TOKEN: ${{ secrets.A_PUSH_TOKEN }}  # Use the PAT stored in GitHub Secrets
      run: |
        git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.A_PUSH_TOKEN }}@github.com/ronia-jakim/knmt-website.git
        git push origin HEAD:main  # Push changes to the main branch (or your specific branch)

