name: Update Submodule content

on:
  schedule:
    - cron: '0 * * * *'  # every hour (UTC)
  workflow_dispatch:     # allows manual trigger

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout website with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Pull latest from submodule content
      run: |
        git submodule update --remote --merge
        git add content
        git commit -m "chore: update submodule content to latest" || echo "No changes to commit"

    - name: Push changes
      run: git push
